name: Build BSS GoB APK + Web

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'
          cache: true
          
      - name: Clean
        run: |
          rm -rf build .dart_tool
          flutter clean
          
      - name: Get packages
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons
        
      - name: Build Web
        run: flutter build web --release
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BSS-GoB-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          
      - name: Upload Web
        uses: actions/upload-artifact@v4
        with:
          name: BSS-GoB-Web
          path: build/web

      - name: Deploy Web to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web